### Get the secret ingredient.
GET https://localhost:7086/secret/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNhcmxvIEFyZWxsYW5vIiwic3ViIjoiQ2FybG8gQXJlbGxhbm8iLCJqdGkiOiI0M2Q2ZWQ0NCIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUxODAiLCJodHRwczovL2xvY2FsaG9zdDo3MDg2Il0sIm5iZiI6MTc1NjM1NzAwMiwiZXhwIjoxNzY0MzA1ODAyLCJpYXQiOjE3NTYzNTcwMDMsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.Co-S0FIHmRNZoPaLBuiBDfR78qMi7hA2udwwGqsy4U8